# Default values for DynamoDB local:
replicaCount: 1

image:
  repository: amazon/dynamodb-local
  tag: latest
  pullPolicy: IfNotPresent

persistence:
  enabled: true
  storageClassName: local-path
  accessMode: ReadWriteOnce
  size: 1Gi

service:
  annotations: {}
  type: ClusterIP
  port: 8000

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
