apiVersion: v2
appVersion: latest
dependencies:
- name: common
  repository: https://library-charts.k8s-at-home.com
  version: 4.4.2
- condition: redis.enabled
  name: redis
  repository: https://charts.pascaliske.dev
  version: 0.0.3
description: SearXNG is a free internet metasearch engine which aggregates results
  from various search services and databases.
icon: https://github.com/searxng/searxng/blob/master/searx/static/themes/simple/img/favicon.png?raw=true
keywords:
- searx
- searxng
- search engine
- privacy
kubeVersion: '>=1.16.0-0'
maintainers:
- email: searxng@unixfoxremovemeifyouwanttocontactme.eu
  name: unixfox
name: searxng
sources:
- https://github.com/searxng/searxng
- https://docs.searxng.org
- https://hub.docker.com/r/searxng/searxng
version: 1.0.1
